### ISSUE TITLE
Improve efficiency of reorder_view

### ISSUE THREAD

**Issue by maxpeterson** [incuna/django-orderable#14]
The `reorder_view` calls save on each model. Since it is dealing with a set of `ids` it could be more efficient to use `update`.

Based on #13 the algorithm could be:
- Find the min and max of the items being reordered.
- Check that the items being reordered fit between the min and max.
- Move items being reordered to the end of the list.
- Update items to be consecutive numbers between min and max.

**Comment by mjtamlyn** [comment]
Using `bulk_update` would bypass `Orderable.save()` and therefore any "jiggery pokery"

**Comment by meshy** [comment]
Yeah, I don't think that `update` is the way to go here.

**Comment by mjtamlyn** [comment]
I would actually say that having a public way of permuting the order of a group of elements in a single query would be very useful, so long as the db is clever enough to know it's a permutation and therefore doesn't break uniqueness. It would make it similar to the `set_RELATED_order` function in django's naive [order with respect to](https://docs.djangoproject.com/en/1.7/ref/models/options/#order-with-respect-to) feature.

**Comment by meshy** [comment]
Sorry didn't mean to close!

**Comment by meshy** [comment]
Using `DEFERRABLE` might be a good solution for this if it ever becomes available.

Ref: https://code.djangoproject.com/ticket/20581

**Comment by Ian-Foote** [comment]
Another possibility is to use fractions as suggested here: https://begriffs.com/posts/2018-03-20-user-defined-order.html

It unfortunately recommends a postgres extension and there's some subtleties, but it might be worth the effort.

**Comment by meshy** [comment]
`connection.constraint_checks_disabled` is worth investigating.

**Comment by maxpeterson** [comment]
Looks like this was addressed in #47
