### ISSUE TITLE
Django 1.5 support

### ISSUE THREAD

**Issue by fonar** [incuna/django-orderable#42]
Fails on Django 1.5 with error:

AttributeError at /admin/
'Options' object has no attribute 'model_name'

\orderable\admin.py in get_url_name, line 43

**Comment by meshy** [comment]
As Django 1.5 is no longer supported, and very likely insecure, I would not advise using it. I do not think that support should be backported for it. I would recommend using either the latest version of Django, or the latest long term support version.
