### ISSUE TITLE
Filter Next/Previous by Relation

### ISSUE THREAD

**Issue by ghickman** [incuna/django-orderable#8]
`next()` & `previous()` methods on `Orderable` filter all orderable models so update them to take an optional relation and filter on.

[Example](https://github.com/incuna/bbo/blob/master/exams/models.py#L15-L26)

**Comment by mjtamlyn** [comment]
These methods now use `get_filtered_manager()` so they will respect `Meta.unique_together`. I think this can be closed.

**Comment by meshy** [comment]
I think that @mjtamlyn's patch does indeed fix this, @ghickman -- the example link is broken however, so please let me know if this should be reopened.
